const faculty = [
  {
    "facultyID": 91,
    "name": "School of Computing (SOC)",
  },
  {
    "facultyID": 92,
    "name": "School of Engineering (SOE)",
  },
  {
    "facultyID": 93,
    "name": "Centre of Excellence for Pre-University Studies (CEPS)",
  },
  {
    "facultyID": 94,
    "name": "School of Hospitality & Culinary Arts (SOHOS)",
  },
  {
    "facultyID": 95,
    "name": "School of Business (SOBIZ)",
  },
  {
    "facultyID": 96,
    "name": "Centre for American Education (CAE)",
  },
  {
    "facultyID": 97,
    "name": "Centre for Australian Degree Programs (CADP)",
  },
];

const lecturer = [
  {
    "lecturerID": 901,
    "name": "Usha Jayahkudy",
    "extension": 376,
    "contactNo": 6310176,
    "facultyID": 91,
  },
  {
    "lecturerID": 902,
    "name": "Asihvini A/P Govinda Pilay",
    "extension": 327,
    "contactNo": 6310127,
    "facultyID": 91,
  },
  {
    "lecturerID": 903,
    "name": "Asvhini Subramaniam",
    "extension": 345,
    "contactNo": 6310145,
    "facultyID": 91,
  },
  {
    "lecturerID": 904,
    "name": "Kavitha A/P Thamadharan",
    "extension": 347,
    "contactNo": 6310147,
    "facultyID": 91,
  },
  {
    "lecturerID": 905,
    "name": "Khadijah Binde Kamarulazizi",
    "extension": 345,
    "contactNo": 6310145,
    "facultyID": 91,
  },
  {
    "lecturerID": 906,
    "name": "Koo Lee Chun",
    "extension": 318,
    "contactNo": 6310118,
    "facultyID": 91,
  },
  {
    "lecturerID": 907,
    "name": "Light Lau Teng Lye",
    "extension": 316,
    "contactNo": 6310116,
    "facultyID": 91,
  },
  {
    "lecturerID": 908,
    "name": "Puteri Nursyawati Binti Azzuri",
    "extension": 301,
    "contactNo": 6310101,
    "facultyID": 91,
  },
  {
    "lecturerID": 909,
    "name": "Shahriman Mohd Said",
    "extension": 347,
    "contactNo": 6310147,
    "facultyID": 91,
  },
  {
    "lecturerID": 910,
    "name": "Teng Wei Jian",
    "extension": 305,
    "contactNo": 6310105,
    "facultyID": 91,
  },
  {
    "lecturerID": 911,
    "name": "Tan Lee Ooi",
    "extension": 376,
    "contactNo": 6310176,
    "facultyID": 92,
  },
  {
    "lecturerID": 912,
    "name": "Nur Hafizah Habideen",
    "extension": 386,
    "contactNo": 6310186,
    "facultyID": 92,
  },
  {
    "lecturerID": 913,
    "name": "Ronald Anak Jackson",
    "extension": 380,
    "contactNo": 6310180,
    "facultyID": 92,
  },
  {
    "lecturerID": 914,
    "name": "Dinash Kandasamy",
    "extension": 243,
    "contactNo": 6310043,
    "facultyID": 93,
  },
  {
    "lecturerID": 915,
    "name": "Tan Bee Hooi",
    "extension": 278,
    "contactNo": 6310078,
    "facultyID": 93,
  },
  {
    "lecturerID": 916,
    "name": "Ooi Saik Huey",
    "extension": 278,
    "contactNo": 6310078,
    "facultyID": 93,
  },
  {
    "lecturerID": 917,
    "name": "Jeff Lim Chang Wei",
    "extension": 382,
    "contactNo": 6310182,
    "facultyID": 94,
  },
  {
    "lecturerID": 918,
    "name": "Clemment Foo Cheok Hwa",
    "extension": 301,
    "contactNo": 6310101,
    "facultyID": 94,
  },
  {
    "lecturerID": 919,
    "name": "Nur Adilah Zulkiply",
    "extension": 345,
    "contactNo": 6310145,
    "facultyID": 94,
  },
  {
    "lecturerID": 920,
    "name": "Khor Kok Chin",
    "extension": 284,
    "contactNo": 6310084,
    "facultyID": 95,
  },
  {
    "lecturerID": 921,
    "name": "Asri Osman",
    "extension": 383,
    "contactNo": 6310083,
    "facultyID": 95,
  },
  {
    "lecturerID": 922,
    "name": "Racheal Poh Su Ying",
    "extension": 309,
    "contactNo": 6310109,
    "facultyID": 95,
  },
  {
    "lecturerID": 923,
    "name": "Wilfred Tan Kwang Shean",
    "extension": 383,
    "contactNo": 6310083,
    "facultyID": 95,
  },
  {
    "lecturerID": 924,
    "name": "Noor Hafizah binti Abdullah",
    "extension": 242,
    "contactNo": 6310042,
    "facultyID": 95,
  },
  {
    "lecturerID": 925,
    "name": "Cheah Wan Theng",
    "extension": 339,
    "contactNo": 6310039,
    "facultyID": 96,
  },
  {
    "lecturerID": 926,
    "name": "Jordan Chuah Peng Aik",
    "extension": 367,
    "contactNo": 6310167,
    "facultyID": 96,
  },
  {
    "lecturerID": 927,
    "name": "Brian John",
    "extension": 315,
    "contactNo": 6310115,
    "facultyID": 96,
  },
  {
    "lecturerID": 928,
    "name": "Calvin Cheah Wei Chieh",
    "extension": 217,
    "contactNo": 6310017,
    "facultyID": 96,
  },
  {
    "lecturerID": 929,
    "name": "Nhivashni Womasuthan",
    "extension": 342,
    "contactNo": 6310105,
    "facultyID": 96,
  },
  {
    "lecturerID": 930,
    "name": "Anni Malar",
    "extension": 328,
    "contactNo": 6310128,
    "facultyID": 97,
  },
  {
    "lecturerID": 931,
    "name": "Nur Sharina Cik Ibrahim",
    "extension": 340,
    "contactNo": 6310140,
    "facultyID": 97,
  },
  {
    "lecturerID": 932,
    "name": "Dr Gan Kia Hui",
    "extension": 350,
    "contactNo": 6310150,
    "facultyID": 97,
  },
  {
    "lecturerID": 933,
    "name": "Beh Yeow Hui",
    "extension": 349,
    "contactNo": 6310149,
    "facultyID": 97,
  },
  {
    "lecturerID": 934,
    "name": "Dr Ismaanzira Bitti Ismail",
    "extension": 306,
    "contactNo": 6310106,
    "facultyID": 97,
  },
];

var globalFacilities = [
  {
    "locationID": 10,
    "name": "Disscussion Room",
    "image": "assets/discussionroom.png",
  },
  {
    "locationID": 11,
    "name": "Music Room",
    "image": "assets/musicroom.png",
  },
  {
    "locationID": 13,
    "name": "Pool Table",
    "image": "assets/pooltable.jpeg",
  },
  {
    "locationID": 14,
    "name": "Ping Pong Table",
    "image": "assets/pingpong.jpeg",
  },
  {
    "locationID": 15,
    "name": "Cinema Room",
    "image": "assets/cinemaroom.png",
  },
];

var programmeData = {
  "campus": [
    {
      "campusID": 0001,
      "name": "INTI International College Penang",
      "image": "assets/penang.jpeg",
    },
    {
      "campusID": 0002,
      "name": "INTI International Subang Jaya",
      "image": "assets/subang.jpeg",
    },
    {
      "campusID": 0003,
      "name": "INTI International Nilai",
      "image": "assets/nilai.jpeg",
    },
  ],
  "areaOfStudy": [
    {
      "areaID": 1000,
      "name": "Business",
      "campusID": 0001,
    },
    {
      "areaID": 1001,
      "name": "Mass Communication",
      "campusID": 0001,
    },
    {
      "areaID": 1002,
      "name": "Computing & IT",
      "campusID": 0001,
    },
    {
      "areaID": 1003,
      "name": "Hospitality & Culinary Arts",
      "campusID": 0001,
    },
    {
      "areaID": 1004,
      "name": "Biotechnology & Life Science",
      "campusID": 0001,
    },
    {
      "areaID": 2000,
      "name": "American Degree Transfer Program",
      "campusID": 0002,
    },
    {
      "areaID": 2001,
      "name": "Interior Design",
      "campusID": 0002,
    },
    {
      "areaID": 2002,
      "name": "Graphic Design",
      "campusID": 0002,
    },
    {
      "areaID": 2003,
      "name": "Engineering",
      "campusID": 0002,
    },
    {
      "areaID": 2004,
      "name": "Art & Design",
      "campusID": 0002,
    },
    {
      "areaID": 3000,
      "name": "Working Professionals",
      "campusID": 0003,
    },
    {
      "areaID": 3001,
      "name": "Health Science",
      "campusID": 0003,
    },
    {
      "areaID": 3002,
      "name": "Pre-University",
      "campusID": 0003,
    },
    {
      "areaID": 3003,
      "name": "Mass Communication",
      "campusID": 0003,
    },
    {
      "areaID": 3004,
      "name": "INTI English Language",
      "campusID": 0003,
    }
  ],
  "programme": [
    {
      "programmeID": "DIEC",
      "campusID": 0001,
      "areaID": 1000,
      "name": "Diploma in E-commerce",
    },
    {
      "programmeID": "DBMF",
      "campusID": 0001,
      "areaID": 1000,
      "name": "Diploma in Business Management-Flexible Learning",
    },
    {
      "programmeID": "DIB",
      "campusID": 0001,
      "areaID": 1000,
      "name": "Diploma in Business",
    },
    {
      "programmeID": "BOB",
      "campusID": 0001,
      "areaID": 1000,
      "name": "Bachelor of Business (3+0)",
    },
    {
      "programmeID": "CIBS",
      "campusID": 0001,
      "areaID": 1000,
      "name": "Certificate in Business Studies",
    },
    {
      "programmeID": "DIMS",
      "campusID": 0001,
      "areaID": 1001,
      "name": "Diploma in Mass Communication",
    },
    {
      "programmeID": "DDM",
      "campusID": 0001,
      "areaID": 1001,
      "name": "Diploma in Digital Media",
    },
    {
      "programmeID": "BMC",
      "campusID": 0001,
      "areaID": 1001,
      "name": "Bachelor of Media Comunication(3+0)",
    },
    {
      "programmeID": "DMC",
      "campusID": 0001,
      "areaID": 1001,
      "name": "Bachelor of Arts(Honours) Mass Communication 3+0",
    },
    {
      "programmeID": "FITN",
      "campusID": 0001,
      "areaID": 1002,
      "name": "Foundation in Information Technology",
    },
    {
      "programmeID": "DITN",
      "campusID": 0001,
      "areaID": 1002,
      "name": "Diploma in Information Technology",
    },
    {
      "programmeID": "DCS",
      "campusID": 0001,
      "areaID": 1002,
      "name": "Diploma in Computer Science",
    },
    {
      "programmeID": "CITN",
      "campusID": 0001,
      "areaID": 1002,
      "name": "Certificate in Information Technology",
    },
    {
      "programmeID": "BSC",
      "campusID": 0001,
      "areaID": 1002,
      "name": "Bachelor of Science with Honours in Computing 3+0",
    },
    {
      "programmeID": "DCA",
      "campusID": 0001,
      "areaID": 1003,
      "name": "Diploma in Culinary Arts",
    },
    {
      "programmeID": "DHM",
      "campusID": 0001,
      "areaID": 1003,
      "name": "Diploma in Hotel Management",
    },
    {
      "programmeID": "SADTP",
      "campusID": 0001,
      "areaID": 1004,
      "name": "Australian Degree Transfer Programme (Science)",
    },
    {
      "programmeID": "SCA",
      "campusID": 0002,
      "areaID": 2000,
      "name": "Summer Course",
    },
    {
      "programmeID": "PDPA",
      "campusID": 0002,
      "areaID": 2000,
      "name": "Psychology Degree Program",
    },
    {
      "programmeID": "MCDPA",
      "campusID": 0002,
      "areaID": 2000,
      "name": "Mass Communication Degree Program",
    },
    {
      "programmeID": "HASPA",
      "campusID": 0002,
      "areaID": 2001,
      "name": "Health and Applied Science Program",
    },
    {
      "programmeID": "EDPA",
      "campusID": 0002,
      "areaID": 2000,
      "name": "Engineering Degree Program",
    },
    {
      "programmeID": "DID",
      "campusID": 0002,
      "areaID": 2001,
      "name": "Diploma in Interior Design",
    },
    {
      "programmeID": "FID",
      "campusID": 0002,
      "areaID": 2001,
      "name": "Foundation in Design",
    },
    {
      "programmeID": "FID",
      "campusID": 0002,
      "areaID": 2002,
      "name": "Foundation in Design",
    },
    {
      "programmeID": "DSD",
      "campusID": 0002,
      "areaID": 2002,
      "name": "Diploma in Immersive Design",
    },
    {
      "programmeID": "DGD",
      "campusID": 0002,
      "areaID": 2002,
      "name": "Diploma in Graphic Design",
    },
    {
      "programmeID": "CAD",
      "campusID": 0002,
      "areaID": 2002,
      "name": "Certificate in Art Design",
    },
    {
      "programmeID": "BGD",
      "campusID": 0002,
      "areaID": 2002,
      "name": "BA(Hons)Graphic Desgn 3+0",
    },
    {
      "programmeID": "DME",
      "campusID": 0002,
      "areaID": 2003,
      "name": "Diploma in Mechanical Engineering",
    },
    {
      "programmeID": "DQS",
      "campusID": 0002,
      "areaID": 2003,
      "name": "Diploma in Quantity Surveying",
    },
    {
      "programmeID": "FIS",
      "campusID": 0002,
      "areaID": 2003,
      "name": "Foundation in Science",
    },
    {
      "programmeID": "FID",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Foundation in Design",
    },
    {
      "programmeID": "DID",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Diploma in Interior Design",
    },
    {
      "programmeID": "DIMD",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Diploma in Immersive Design",
    },
    {
      "programmeID": "DGD",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Diploma in Graphic Design",
    },
    {
      "programmeID": "DFD",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Diploma in Fashion Design",
    },
    {
      "programmeID": "CAD",
      "campusID": 0002,
      "areaID": 2004,
      "name": "Certificate in Art & Design",
    },
    {
      "programmeID": "MSIT",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Master of Science in Innovation and Technology (by Research)",
    },
    {
      "programmeID": "MSDS",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Master of Science in Data Science (by Research)",
    },
    {
      "programmeID": "MSCM-FM",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Master of Science in Construction Management (Facility Management)",
    },
    {
      "programmeID": "MSCM-BIM",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Master of Science in Construcation Management (Building Information Modelling)-(Fully Online)",
    },
    {
      "programmeID": "DBO",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Diploma in Business (Online Learning)",
    },
    {
      "programmeID": "DBA",
      "campusID": 0003,
      "areaID": 3000,
      "name": "Doctor of Business Administration",
    },
    {
      "programmeID": "MHA",
      "campusID": 0003,
      "areaID": 3001,
      "name": "Master in Health Administration",
    },
    {
      "programmeID": "BTCM",
      "campusID": 0003,
      "areaID": 3001,
      "name": "Bachelor of Traditional Chinese Medicine(Hons)",
    },
    {
      "programmeID": "BSP",
      "campusID": 0003,
      "areaID": 3001,
      "name": "B.Sc.(Hons) in Physiotherapy",
    },
    {
      "programmeID": "MHSP",
      "campusID": 0003,
      "areaID": 3001,
      "name": "Master in Health Sciences (Physiotherapy)(by Research)",
    },
    {
      "programmeID": "FIA",
      "campusID": 0003,
      "areaID": 3002,
      "name": "Foundation in Arts",
    },
    {
      "programmeID": "FIB",
      "campusID": 0003,
      "areaID": 3002,
      "name": "Foundation in Business",
    },
    {
      "programmeID": "FITN",
      "campusID": 0003,
      "areaID": 3002,
      "name": "Foundation in Information Technology",
    },
    {
      "programmeID": "FIS",
      "campusID": 0003,
      "areaID": 3002,
      "name": "Foundation in Science",
    },
    {
      "programmeID": "FIA",
      "campusID": 0003,
      "areaID": 3003,
      "name": "Foundation in Arts",
    },
    {
      "programmeID": "DMC",
      "campusID": 0003,
      "areaID": 3003,
      "name": "Diploma in Mass Communication",
    },
    {
      "programmeID": "BMC",
      "campusID": 0003,
      "areaID": 3003,
      "name": "Bachelor of Mass Communication(Hons)",
    },
    {
      "programmeID": "IETC",
      "campusID": 0003,
      "areaID": 3004,
      "name": "IELTS Training Course",
    },
    {
      "programmeID": "IEP",
      "campusID": 0003,
      "areaID": 3003,
      "name": "Intensive English Programme(IEP)",
    }
  ],
};

const foodCategory = [
  {
    "foodCategoryID": 21,
    "name": "Rice",
  },
  {
    "foodCategoryID": 22,
    "name": "Bread",
  },
  {
    "foodCategoryID": 23,
    "name": "Noodle",
  },
  {
    "foodCategoryID": 24,
    "name": "Western",
  },
];

const foodData = [
  {
    "foodID": 2001,
    "name": "Nasi Lemak",
    "price": 10.00,
    "image": "assets/nasilemak.jpeg",
    "foodCategoryID": 21,
  },
  {
    "foodID": 2002,
    "name": "Fried Rice",
    "price": 6.00,
    "image": "assets/friedrice.jpeg",
    "foodCategoryID": 21,
  },
  {
    "foodID": 2003,
    "name": "Nasi Biryani",
    "price": 12.00,
    "image": "assets/biryani.jpeg",
    "foodCategoryID": 21,
  },
  {
    "foodID": 2004,
    "name": "Roti Bakar",
    "price": 3.00,
    "image": "assets/rotibakar.png",
    "foodCategoryID": 22,
  },
  {
    "foodID": 2005,
    "name": "Butter + Kaya",
    "price": 5.00,
    "image": "assets/butterkaya.jpeg",
    "foodCategoryID": 22,
  },
  {
    "foodID": 2006,
    "name": "Peanut Butter",
    "price": 4.00,
    "image": "assets/peanutbutter.jpeg",
    "foodCategoryID": 22,
  },
  {
    "foodID": 2007,
    "name": "Bread + Butter",
    "price": 3.00,
    "image": "assets/butter.jpeg",
    "foodCategoryID": 22,
  },
  {
    "foodID": 2008,
    "name": "Fried Noodle",
    "price": 5.00,
    "image": "assets/friednoodle.jpeg",
    "foodCategoryID": 23,
  },
  {
    "foodID": 2009,
    "name": "Bihun Goreng",
    "price": 5.00,
    "image": "assets/bihungoreng.jpeg",
    "foodCategoryID": 23,
  },
  {
    "foodID": 2010,
    "name": "Tomyam Bihun",
    "price": 4.00,
    "image": "assets/tomyambihun.jpeg",
    "foodCategoryID": 23,
  },
  {
    "foodID": 2011,
    "name": "Maggie",
    "price": 6.00,
    "image": "assets/maggiegoreng.jpeg",
    "foodCategoryID": 23,
  },
  {
    "foodID": 2012,
    "name": "Spaghetti",
    "price": 8.00,
    "image": "assets/spaghetti.jpeg",
    "foodCategoryID": 24,
  },
  {
    "foodID": 2013,
    "name": "Carbonara",
    "price": 6.00,
    "image": "assets/carbonara.jpeg",
    "foodCategoryID": 24,
  },
  {
    "foodID": 2014,
    "name": "Chicken Chop",
    "price": 12.00,
    "image": "assets/chickenchop.jpeg",
    "foodCategoryID": 24,
  },
  {
    "foodID": 2015,
    "name": "Black Pepper Chicken",
    "price": 14.00,
    "image": "assets/blackpepper.jpeg",
    "foodCategoryID": 24,
  },
  {
    "foodID": 2016,
    "name": "Fish & Chip",
    "price": 12.00,
    "image": "assets/fishnchip.jpeg",
    "foodCategoryID": 24,
  },
];